config/routes.rb
AppManager::Application.routes.draw do

  root to: "home#index"
  get 'sign_in' => 'sessions#create'
  get 'sign_out' => 'sessions#destroy'

  namespace :super_admin do

    get 'home' => 'super_admin#index'
    resources :users
    resources :companies do
        resources :apps
        get 'roles' => "company_users#index"
        put 'save' => "company_users#update"
    end

    resources :apps, :only => [] do
      resources :versions do
        get 'invite_by_email' => "versions#invite_by_email"
      end
    end

  end

  get 'dashboard' => 'globalmembers#index'

  namespace :admin do

    resources :companies do
      resources :users
      resources :apps
      get 'roles' => "company_users#index"
      put 'save' => "company_users#update"
    end
    resources :users
    resources :apps, :only => [] do
      resources :versions do
        get 'invite_by_email' => "versions#invite_by_email"
      end
    end

  end

  namespace :developer do
    resources :apps, :only => [] do
      resources :versions do
        get 'invite_by_email' => "versions#invite_by_email"
      end
    end
    resources :companies, :only => [:show, :index] do
      resources :apps
      resources :users
    end
  end

  namespace :member do
    resources :companies, :only => [:show]
    resources :apps, :only => [:show, :index]
  end

  get '/email-:vid' => 'home#download_email'
  get '/:vid' => 'home#download'
  

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :company_users # dependency
	has_many :users, :through => :company_users
	has_many :apps

	validates_presence_of :name

	#this is not right
	before_create :set_default

	def assign_admin(user)
		@company_user = self.company_users.find_by_user_id(user.id)
		if @company_user
			@company_user.role = CompanyUser::ADMIN
			@company_user.save
		end
	end



private

# your model is shared by all controller, whether it's admin/normal user. 
# doing this means you can't initialize what you want in admin
# what you can do
	# def self.initiate_with_default(args)
	# 	temp = Company.new(args)
	# 	temp.is_active = false
	# 	temp.max_admin = 2
	# 	temp
	# end


def set_default
	self.is_active = false
	self.max_admin = 2
end

end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::AdminsController
	before_filter :check_admin_user, :except => [:show, :new, :create]
	before_filter :check_inactive_company, :only => [:new,:create]
	
	def new
		@company = Company.new
	end

	def create
		# user can keep creating company even after not being approved! this should not be allowed for more than 1 inactive company
		@company = Company.new(company_parameters)
		if @company.save
			@company.assign_attributes(company_user_parameters)
			@company.assign_admin(current_user)
			if @company.save
				redirect_to admin_company_path(@company)
			else
				render "new"
			end
		else
			render "new"
		end
	end

	def edit
		@company = get_entity Company.find_by_id(params[:id])
	end
		
	def update
		@company = get_entity Company.find_by_id(params[:id])
		@company.assign_attributes(company_user_parameters)
		if @company.save
			redirect_to admin_company_path(@company)
		else
			render "edit"
		end
	end

	def show
		set_company(get_entity Company.find_by_id(params[:id]))
		@company = current_company
		@user = current_user
		@company_users = CompanyUser.find_all_by_company_id(@company.id)
	end

	private

	def company_user_parameters
		params.require(:company).permit(:name, :address, :phone, :max_admin, :is_active, :user_ids => [])
	end


	def company_parameters
		params.require(:company).permit(:name, :address, :phone, :max_admin, :is_active)
	end

	# partially, the business logic shouldn't be in controller here
	# you can move into business logic area/model and just return true/false so that your logic can be shared across the system
	def check_inactive_company
		@company_users = CompanyUser.where(:user_id => current_user.id, :role => CompanyUser::ADMIN)
		@company_users.each do |c_user|
			@company = get_entity Company.find_by_id(c_user.company_id)
			unless @company.is_active
				flash[:notice] = "You already have an inactive company waiting for approval. Please wait for its approval before proceeding."
				redirect_to root_path
			end
		end
	end

end

app/controllers/developer/companies_controller.rb
class Developer::CompaniesController < Developer::DevelopersController
	before_filter :check_developer_user, :except => [:show]
	before_filter :check_inactive_company, :only => [:new,:create]

	def new
		@company = Company.new
	end

	def create
		@company = Company.new(company_parameters)
		if @company.save
			@company.assign_attributes(company_user_parameters)
			if @company.save
				redirect_to developer_company_path(@company)
			else
				render "new"
			end
		else
			render "new"
		end
	end

	def edit
		@company = get_entity Company.find_by_id(params[:id])
	end
		
	def update
		@company = get_entity Company.find_by_id(params[:id])
		@company.assign_attributes(company_user_parameters)
		if @company.save
			redirect_to developer_company_path(@company)
		else
			render "edit"
		end
	end

	def show
		set_company(get_entity Company.find_by_id(params[:id]))
		@company = current_company
		@user = current_user
		@company_users = CompanyUser.find_all_by_company_id(@company.id)
	end

	private

	def company_user_parameters
		params.require(:company).permit(:name, :address, :phone, :max_admin, :is_active, :user_ids => [])
	end


	def company_parameters
		params.require(:company).permit(:name, :address, :phone, :max_admin, :is_active)
	end

	def check_inactive_company
		@company_users = CompanyUser.where(:user_id => current_user.id, :role => CompanyUser::ADMIN)
		@company_users.each do |c_user|
			@company = get_entity Company.find_by_id(c_user.company_id)
			unless @company.is_active
				flash[:notice] = "You already have an inactive company waiting for approval. Please wait for its approval before proceeding."
				redirect_to root_path
			end
		end
	end

end

app/controllers/member/companies_controller.rb
class Member::CompaniesController < Member::MembersController
	before_filter :check_member_user, :except => [:show]
	before_filter :check_inactive_company, :only => [:new,:create]


	def show
		set_company(get_entity Company.find_by_id(params[:id]))
		@company = current_company
		@user = current_user
		@company_users = CompanyUser.find_all_by_company_id(@company.id)
	end

	def check_inactive_company
		@company_users = CompanyUser.where(:user_id => current_user.id, :role => CompanyUser::ADMIN)
		@company_users.each do |c_user|
			@company = get_entity Company.find_by_id(c_user.company_id)
			unless @company.is_active
				flash[:notice] = "You already have an inactive company waiting for approval. Please wait for its approval before proceeding."
				redirect_to root_path
			end
		end
	end

	
end

app/controllers/super_admin/companies_controller.rb
class SuperAdmin::CompaniesController < SuperAdmin::SuperAdminController

	def index
		@companies = Company.all
	end

	def new
		@company = Company.new
	end

	def create
		@company = Company.new(company_parameters)
		if @company.save
			@company.assign_attributes(company_user_parameters)
			if @company.save
				redirect_to super_admin_company_path(@company)
			else
				render "new"
			end
		else
			render "new"
		end
	end

	def edit
		@company = get_entity Company.find_by_id(params[:id])
	end
		
	def update
		@company = get_entity Company.find_by_id(params[:id])
		@company.assign_attributes(company_user_parameters)
		if @company.save
			redirect_to super_admin_company_path(@company)
		else
			render "edit"
		end
	end

	def show
		@company = get_entity Company.find_by_id(params[:id])
		@company_users = CompanyUser.find_all_by_company_id(@company.id)
	end

	def destroy
		@company = get_entity Company.find_by_id(params[:id])
		@company.destroy
	end


	private

	def company_user_parameters
		params.require(:company).permit(:name, :address, :phone, :max_admin, :is_active, :user_ids => [])
	end


	def company_parameters
		params.require(:company).permit(:name, :address, :phone, :max_admin, :is_active)
	end

end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/developer/companies_helper.rb
module Developer::CompaniesHelper
end

app/helpers/member/companies_helper.rb
module Member::CompaniesHelper
end

app/helpers/super_admin/companies_helper.rb
module SuperAdmin::CompaniesHelper
end

app/views/admin/companies/edit.html.erb
<%= form_for @company, :as => :company, :url => admin_company_path(@company), :method => :put, :html => {:multipart => true } do |f| %>

	<% if @company.errors.any? %>
		<ul>
  			<% @company.errors.full_messages.each do |msg| %>
    			<li><%= msg %></li>
  			<% end %>
		</ul>
	<% end %>


	<div class="title-2"> 
	      	<%= f.label :name, "Name*" %>
	      	<%= f.text_field :name, :size => "30" %>
	</div>

	<div class="title-2"> 
	      	<%= f.label :address, "Address*" %>
	      	<%= f.text_field :address %>
	</div>

	<div class="title-2"> 
	      	<%= f.label :phone, "Phone*" %>
	      	<%= f.text_field :phone, :size => "30" %>
	</div>

	<div class="field">
     <%= f.label :members %><br>
     <%= f.collection_select(:user_ids, User.all.collect, :id, :name, {:prompt => "Please select"}, {:multiple => true} ) %>
	</div>
  


	<%= f.submit "Save", style: "width:120px; height:35px; background-color:#c25b39; border:1px solid #c25b39; color:#FFF; font-size:17px; float:left; margin-right:180px;" %>

<% end %>

app/views/admin/companies/new.html.erb
<%= form_for @company, :as => :company, :url => admin_companies_path(@company), :method => :post, :html => {:multipart => true } do |f| %>

	<% if @company.errors.any? %>
		<ul>
  			<% @company.errors.full_messages.each do |msg| %>
    			<li><%= msg %></li>
  			<% end %>
		</ul>
	<% end %>


	<div class="title-2"> 
	      	<%= f.label :name, "Name*" %>
	      	<%= f.text_field :name, :size => "30" %>
	</div>

	<div class="title-2"> 
	      	<%= f.label :address, "Address*" %>
	      	<%= f.text_field :address %>
	</div>

	<div class="title-2"> 
	      	<%= f.label :phone, "Phone*" %>
	      	<%= f.text_field :phone, :size => "30" %>
	</div>


	<!-- why members here? what do members here mean? admin/dev/normal_member? if so, it can only assign after being admin -->
	<div class="field">
     <%= f.label :members %><br>
     <%= f.collection_select(:user_ids, User.all.collect, :id, :name, {:prompt => "Please select"}, {:multiple => true} ) %>
	</div>
  


	<%= f.submit "Submit", style: "width:120px; height:35px; background-color:#c25b39; border:1px solid #c25b39; color:#FFF; font-size:17px; float:left; margin-right:180px;" %>

<% end %>

app/views/admin/companies/show.html.erb
<%= link_to 'Dashboard', dashboard_path %>
<p>Name: <%= @company.name %></p>
	<p>Phone: <%= @company.phone %></p>
	<p>Address: <%= @company.address %></p>
	<p>Max Admins: <%= @company.max_admin %></p>
	<p>Active: <%= @company.is_active %></p>

	<h3>Users </h3>

	<% @company_users.each do |c_user| %>
		<p> Name: <%= c_user.user.name %></p>
		<p> Role: <%= c_user.role %></p>
	<% end %>	

	<h3>Applications</h3>

	<% @company.apps.each do |app| %>
		<p> Name: <%= app.name %></p>
		<%= link_to 'View App Details', admin_company_app_path(@company,app) %>
	<% end %>	

	<h3> Other Options </h3>

	<%= link_to 'Edit User Roles', admin_company_roles_path(@company) %>
	<br>

	<%= link_to 'Edit Company', edit_admin_company_path(@company) %>

	<br>

	<%= link_to 'Add a User', new_admin_company_user_path(@company) %>
	<br>

	<%= link_to 'Create an App', new_admin_company_app_path(@company) %>
	

	