config/routes.rb
AppManager::Application.routes.draw do

  root to: "home#index"
  get 'sign_in' => 'sessions#create'
  get 'sign_out' => 'sessions#destroy'

  namespace :super_admin do

    get 'home' => 'super_admin#index'
    resources :users
    resources :companies do
        resources :apps
        get 'roles' => "company_users#index"
        put 'save' => "company_users#update"
    end

    resources :apps, :only => [] do
      resources :versions do
        get 'invite_by_email' => "versions#invite_by_email"
      end
    end

  end

  get 'dashboard' => 'globalmembers#index'

  namespace :admin do

    resources :companies do
      resources :users
      resources :apps
      get 'roles' => "company_users#index"
      put 'save' => "company_users#update"
    end
    resources :users
    resources :apps, :only => [] do
      resources :versions do
        get 'invite_by_email' => "versions#invite_by_email"
      end
    end

  end

  namespace :developer do
    resources :apps, :only => [] do
      resources :versions do
        get 'invite_by_email' => "versions#invite_by_email"
      end
    end
    resources :companies, :only => [:show, :index] do
      resources :apps
      resources :users
    end
  end

  namespace :member do
    resources :companies, :only => [:show]
    resources :apps, :only => [:show, :index]
  end

  get '/email-:vid' => 'home#download_email'
  get '/:vid' => 'home#download'
  

end

app/controllers/globalmembers_controller.rb
class GlobalmembersController < ApplicationController

	def index
		@company_users = CompanyUser.find_all_by_user_id(current_user.id)
	end

end

app/helpers/globalmembers_helper.rb
module GlobalmembersHelper
end

app/views/globalmembers/index.html.erb
<%=  link_to 'Sign Out', sign_out_path %>
<%=  link_to 'Create Company', new_admin_company_path %>
<br>


<% @company_users.each do |c_user| %>

<p> Company: <%= c_user.company.name %> </p>
<p> Role: <%= c_user.role %> </p>
<% if c_user.is_admin? %>
<%=  link_to 'View As Admin', admin_company_path(c_user.company) %>
<% elsif c_user.is_developer? %>
<%=  link_to 'View As Developer', developer_company_path(c_user.company) %>
<% else %>
<%=  link_to 'View As Member', member_company_path(c_user.company) %>
<% end %>

<% end %>