config/routes.rb
AppManager::Application.routes.draw do

  root to: "home#index"
  get 'sign_in' => 'sessions#create'
  get 'sign_out' => 'sessions#destroy'

  namespace :super_admin do

    get 'home' => 'super_admin#index'
    resources :users
    resources :companies do
        resources :apps
        get 'roles' => "company_users#index"
        put 'save' => "company_users#update"
    end

    resources :apps, :only => [] do
      resources :versions do
        get 'invite_by_email' => "versions#invite_by_email"
      end
    end

  end

  get 'dashboard' => 'globalmembers#index'

  namespace :admin do

    resources :companies do
      resources :users
      resources :apps
      get 'roles' => "company_users#index"
      put 'save' => "company_users#update"
    end
    resources :users
    resources :apps, :only => [] do
      resources :versions do
        get 'invite_by_email' => "versions#invite_by_email"
      end
    end

  end

  namespace :developer do
    resources :apps, :only => [] do
      resources :versions do
        get 'invite_by_email' => "versions#invite_by_email"
      end
    end
    resources :companies, :only => [:show, :index] do
      resources :apps
      resources :users
    end
  end

  namespace :member do
    resources :companies, :only => [:show]
    resources :apps, :only => [:show, :index]
  end

  get '/email-:vid' => 'home#download_email'
  get '/:vid' => 'home#download'
  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :company_users
	has_many :companies, :through => :company_users

	has_secure_password


	validates_presence_of :name, :password_digest, :email
	# where is email validation format?
	validates_uniqueness_of :email

	before_create :create_remember_token


	def is_super_admin?
		self.is_super_admin == true
	end


	private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminsController
# edit/update/destroy?	
	def new
		@company = get_entity Company.find_by_id(params[:company_id])
		@user = User.new
	end

	def create
		@company = get_entity Company.find_by_id(params[:company_id])
		@user = User.new(user_parameters)
		if @user.save
			@user.companies.push(@company)
			if @user.save
				redirect_to admin_company_user_path(@company,@user)
			else
				render "new"
			end
		else
			render "new"
		end
	end

	def show
		@company = get_entity Company.find_by_id(params[:company_id])
		@user = get_entity User.find_by_id(params[:id])
	end

	private

	def user_parameters
		params.require(:user).permit(:name, :password, :password_confirmation, :email)
	end

end

app/controllers/developer/users_controller.rb
class Developer::UsersController < Developer::DevelopersController

	def new
		@company = get_entity Company.find_by_id(params[:company_id])
		@user = User.new
	end

	def create
		@company = get_entity Company.find_by_id(params[:company_id])
		@user = User.new(user_parameters)
		if @user.save
			@user.companies.push(@company)
			if @user.save
				redirect_to developer_company_user_path(@company,@user)
			else
				render "new"
			end
		else
			render "new"
		end
	end

	def show
		@company = get_entity Company.find_by_id(params[:company_id])
		@user = get_entity User.find_by_id(params[:id])
	end

	private

	def user_parameters
		params.require(:user).permit(:name, :password, :password_confirmation, :email)
	end

end

app/controllers/super_admin/users_controller.rb
class SuperAdmin::UsersController < SuperAdmin::SuperAdminController
	# where are the "edit" and "update" actions?
	
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_parameters)
		if @user.save
			redirect_to super_admin_user_path(@user)
		else
			render "new"
		end
	end

	def show
		@user = get_entity User.find_by_id(params[:id])
	end

	def destroy
		@user = get_entity User.find_by_id(params[:id])
		@user.destroy
	end


	private

	def user_parameters
		params.require(:user).permit(:name, :password, :password_confirmation, :email)
	end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/developer/users_helper.rb
module Developer::UsersHelper
end

app/helpers/super_admin/users_helper.rb
module SuperAdmin::UsersHelper
end

app/views/admin/users/new.html.erb
<%= form_for @user, :as => :user, :url => admin_company_users_path(@company,@user), :method => :post, :html => {:multipart => true } do |f| %>

	<% if @user.errors.any? %>
		<ul>
  			<% @user.errors.full_messages.each do |msg| %>
    			<li><%= msg %></li>
  			<% end %>
		</ul>
	<% end %>

	
	<div class="title-2"> 
	      	<%= f.label :name, "Name*" %>
	      	<%= f.text_field :name, :size => "30" %>
	</div>

	<div class="title-2"> 
	      	<%= f.label :email, "Email*" %>
	      	<%= f.text_field :email %>
	</div>

	<div class="title-2"> 
	      	<%= f.label :password, "Password*" %>
	      	<%= f.text_field :password, :size => "30" %>
	</div>

	<div class="title-2"> 
	      	<%= f.label :password_confirmation, "Password Confirmation*" %>
	      	<%= f.text_field :password_confirmation, :size => "30" %>
	</div>

	


	<%= f.submit "Submit", style: "width:120px; height:35px; background-color:#c25b39; border:1px solid #c25b39; color:#FFF; font-size:17px; float:left; margin-right:180px;" %>

<% end %>

app/views/admin/users/show.html.erb
<p>Go Back To <%=  link_to 'Company', admin_company_path(@company) %></p>

<p>Name: <%= @user.name %></p>
	<p>Email: <%= @user.email %></p>
	<p>Companies</p>
	<% @user.companies.each do |company| %>
		<p> <%= company.name %></p>
	<% end %>